import { RawBoard, Currency, Region } from "./types";
import { BrandIdentifier } from "./strategies/brand-identifier";

/**
 * Seed data for development and demo purposes.
 * These represent real snowboards with realistic pricing from the 2024-2025 season.
 * Used when live scraping is unavailable (Cloudflare/bot protection).
 */
export const SEED_BOARDS: RawBoard[] = [
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/burton-ripcord",
    imageUrl: undefined,
    brand: new BrandIdentifier("Burton"),
    model: "Ripcord",
    year: 2025,
    lengthCm: 157,
    widthMm: 252,
    flex: "Soft (3/10)",
    profile: "Flat Top",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 399.95,
    salePrice: 279.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Burton Ripcord is a beginner-friendly board with a flat profile for easy turn initiation and a soft flex for forgiving rides. Directional twin shape works great for learning.",
    specs: { "flex rating": "3/10", "profile": "Flat Top", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/ride-algorythm",
    imageUrl: undefined,
    brand: new BrandIdentifier("Ride"),
    model: "Algorythm",
    year: 2024,
    lengthCm: 158,
    widthMm: 254,
    flex: "Medium-Soft (4/10)",
    profile: "Hybrid Rocker",
    shape: "True Twin",
    category: "All-Mountain/Freestyle",
    originalPrice: 449.95,
    salePrice: 269.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Ride Algorythm features a rocker-dominant hybrid profile for easy, catch-free riding with a true twin shape for switch riding. Great progression board.",
    specs: { "flex rating": "4/10", "profile": "Hybrid Rocker", "shape": "True Twin", "terrain": "All-Mountain, Freestyle" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/k2-standard",
    imageUrl: undefined,
    brand: new BrandIdentifier("K2"),
    model: "Standard",
    year: 2025,
    lengthCm: 158,
    widthMm: 250,
    flex: "Soft (3/10)",
    profile: "Catch Free Rocker Baseline",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 349.95,
    salePrice: 244.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The K2 Standard is an easy-riding, catch-free board designed for beginners. Flat/rocker profile with soft flex makes turn initiation effortless.",
    specs: { "flex rating": "3/10", "profile": "Catch Free Rocker Baseline", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/rossignol-district",
    imageUrl: undefined,
    brand: new BrandIdentifier("Rossignol"),
    model: "District",
    year: 2024,
    lengthCm: 156,
    widthMm: 248,
    flex: "Soft (3/10)",
    profile: "AmpTek Auto-Turn Rocker",
    shape: "True Twin",
    category: "All-Mountain/Freestyle",
    originalPrice: 329.95,
    salePrice: 197.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "A forgiving twin board with rocker profile for easy turning. Great value for beginner riders looking for a versatile all-mountain freestyle board.",
    specs: { "flex rating": "3/10", "profile": "AmpTek Auto-Turn Rocker", "shape": "True Twin", "terrain": "All-Mountain, Freestyle" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/salomon-pulse",
    imageUrl: undefined,
    brand: new BrandIdentifier("Salomon"),
    model: "Pulse",
    year: 2024,
    lengthCm: 160,
    widthMm: 253,
    flex: "Soft-Medium (4/10)",
    profile: "Flat",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 369.95,
    salePrice: 258.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "A mellow, easy-riding board with flat profile and forgiving flex. The Pulse is designed to help new riders progress quickly on all terrain.",
    specs: { "flex rating": "4/10", "profile": "Flat", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/gnu-money",
    imageUrl: undefined,
    brand: new BrandIdentifier("GNU"),
    model: "Money",
    year: 2025,
    lengthCm: 158,
    widthMm: 252,
    flex: "Medium (5/10)",
    profile: "C2 BTX",
    shape: "True Twin",
    category: "All-Mountain/Freestyle",
    originalPrice: 499.95,
    salePrice: 349.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The GNU Money features C2 hybrid camber for pop and edge hold with rocker between the feet for easy turn initiation. True twin shape for riding switch.",
    specs: { "flex rating": "5/10", "profile": "C2 BTX", "shape": "True Twin", "terrain": "All-Mountain, Freestyle" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/capita-horrorscope",
    imageUrl: undefined,
    brand: new BrandIdentifier("Capita"),
    model: "Horrorscope",
    year: 2024,
    lengthCm: 155,
    widthMm: 248,
    flex: "Medium-Soft (4/10)",
    profile: "Resort V1",
    shape: "True Twin",
    category: "Park",
    originalPrice: 419.95,
    salePrice: 293.97,
    currency: Currency.USD,
    availability: "low_stock",
    description: "A park-oriented twin board with a playful flex and hybrid camber profile. Good for progressing into park riding, though more specialized than a pure all-mountain board.",
    specs: { "flex rating": "4/10", "profile": "Resort V1", "shape": "True Twin", "terrain": "Park" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/burton-process",
    imageUrl: undefined,
    brand: new BrandIdentifier("Burton"),
    model: "Process",
    year: 2024,
    lengthCm: 159,
    widthMm: 254,
    flex: "Medium (5/10)",
    profile: "Pure Pop Camber",
    shape: "True Twin",
    category: "All-Mountain/Freestyle",
    originalPrice: 529.95,
    salePrice: 370.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Burton Process is a versatile twin board with full camber for edge hold and pop. Medium flex offers a good balance but may be less forgiving for pure beginners.",
    specs: { "flex rating": "5/10", "profile": "Pure Pop Camber", "shape": "True Twin", "terrain": "All-Mountain, Freestyle" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/arbor-foundation",
    imageUrl: undefined,
    brand: new BrandIdentifier("Arbor"),
    model: "Foundation",
    year: 2025,
    lengthCm: 157,
    widthMm: 251,
    flex: "Soft (3/10)",
    profile: "System Rocker",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 359.95,
    salePrice: 251.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Arbor Foundation is a beginner-oriented board with full rocker profile for easy, forgiving turns. Sustainable construction with eco-friendly materials.",
    specs: { "flex rating": "3/10", "profile": "System Rocker", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/nidecker-micron-sensor",
    imageUrl: undefined,
    brand: new BrandIdentifier("Nidecker"),
    model: "Sensor",
    year: 2025,
    lengthCm: 159,
    widthMm: 253,
    flex: "Soft-Medium (4/10)",
    profile: "Hybrid Rocker",
    shape: "True Twin",
    category: "All-Mountain",
    originalPrice: 379.95,
    salePrice: 227.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Nidecker Sensor is a true twin with hybrid rocker for a catch-free, forgiving ride. Great for beginners who want to progress into freestyle.",
    specs: { "flex rating": "4/10", "profile": "Hybrid Rocker", "shape": "True Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/jones-mountain-twin",
    imageUrl: undefined,
    brand: new BrandIdentifier("Jones"),
    model: "Mountain Twin",
    year: 2024,
    lengthCm: 157,
    widthMm: 252,
    flex: "Medium-Stiff (6/10)",
    profile: "CamRock 2.0",
    shape: "Directional Twin",
    category: "All-Mountain/Freeride",
    originalPrice: 549.95,
    salePrice: 384.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Jones Mountain Twin is a versatile all-mountain board with camber-dominant hybrid profile. Stiffer flex provides stability at speed but is less forgiving for beginners.",
    specs: { "flex rating": "6/10", "profile": "CamRock 2.0", "shape": "Directional Twin", "terrain": "All-Mountain, Freeride" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/nitro-prime",
    imageUrl: undefined,
    brand: new BrandIdentifier("Nitro"),
    model: "Prime",
    year: 2025,
    lengthCm: 158,
    widthMm: 253,
    flex: "Soft (3/10)",
    profile: "Flat",
    shape: "True Twin",
    category: "All-Mountain",
    originalPrice: 319.95,
    salePrice: 223.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Nitro Prime is a staple beginner board with flat profile and soft flex for easy turn initiation. True twin shape for switch riding from day one.",
    specs: { "flex rating": "3/10", "profile": "Flat", "shape": "True Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/lib-tech-cold-brew",
    imageUrl: undefined,
    brand: new BrandIdentifier("Lib Tech"),
    model: "Cold Brew",
    year: 2024,
    lengthCm: 157,
    widthMm: 250,
    flex: "Soft-Medium (4/10)",
    profile: "BTX",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 469.95,
    salePrice: 328.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "The Lib Tech Cold Brew features banana rocker for a loose, playful ride. Magne-Traction edges grip on ice. Eco-friendly construction.",
    specs: { "flex rating": "4/10", "profile": "BTX", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/rome-agent",
    imageUrl: undefined,
    brand: new BrandIdentifier("Rome"),
    model: "Agent",
    year: 2024,
    lengthCm: 158,
    widthMm: 253,
    flex: "Medium (5/10)",
    profile: "Hybrid Camber",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 449.95,
    salePrice: 314.97,
    currency: Currency.USD,
    availability: "in_stock",
    description: "A versatile all-mountain board with hybrid camber profile. Medium flex provides a balance of playfulness and stability, suited for progressing intermediates.",
    specs: { "flex rating": "5/10", "profile": "Hybrid Camber", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
  {
    retailer: "evo",
    region: Region.US,
    url: "https://www.evo.com/snowboards/bataleon-goliath",
    imageUrl: undefined,
    brand: new BrandIdentifier("Bataleon"),
    model: "Goliath",
    year: 2024,
    lengthCm: 157,
    widthMm: 254,
    flex: "Medium (5/10)",
    profile: "Camber",
    shape: "Directional Twin",
    category: "All-Mountain",
    originalPrice: 499.95,
    salePrice: 349.97,
    currency: Currency.USD,
    availability: "low_stock",
    description: "The Bataleon Goliath features 3BT triple base technology for catch-free riding despite its camber profile. Good for progressing riders who want more edge hold.",
    specs: { "flex rating": "5/10", "profile": "Camber", "shape": "Directional Twin", "terrain": "All-Mountain" },
    scrapedAt: new Date().toISOString(),
  },
];
